log syslog all;
router id 192.168.14.88;

protocol device {
}

protocol direct {
    ipv4;
}

protocol kernel {
    persist;
    ipv4 {
        export all;
    };
}

protocol rip {
    ipv4 {
        import all;
        export filter {
            if (net ~ [192.168.14.0/24]) then {
                if ((net.len = 32) && (proto ~ "service_")) then accept;
            }
            reject;
        };
    };

    interface "enp3s0" {
        version 2;
        authentication none;
    };
}
